#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SONIC_PRD")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<T_PARTY_MASTER> T_PARTY_MASTERs
	{
		get
		{
			return this.GetTable<T_PARTY_MASTER>();
		}
	}
	
	public System.Data.Linq.Table<T_RM_MASTER> T_RM_MASTERs
	{
		get
		{
			return this.GetTable<T_RM_MASTER>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_PARTY_MASTER")]
public partial class T_PARTY_MASTER
{
	
	private string _T_PARTYM_NAME;
	
	private string _T_PARTYM_ADDRESS;
	
	private System.Nullable<double> _T_PARTYM_DISCOUNT;
	
	private string _T_PARTYM_SPDISCOUNT;
	
	private string _T_PARTYM_CASHDISCOUNT;
	
	private string _T_PARTYM_GSTNUM;
	
	public T_PARTY_MASTER()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_NAME", DbType="NVarChar(255)")]
	public string T_PARTYM_NAME
	{
		get
		{
			return this._T_PARTYM_NAME;
		}
		set
		{
			if ((this._T_PARTYM_NAME != value))
			{
				this._T_PARTYM_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_ADDRESS", DbType="NVarChar(255)")]
	public string T_PARTYM_ADDRESS
	{
		get
		{
			return this._T_PARTYM_ADDRESS;
		}
		set
		{
			if ((this._T_PARTYM_ADDRESS != value))
			{
				this._T_PARTYM_ADDRESS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_DISCOUNT", DbType="Float")]
	public System.Nullable<double> T_PARTYM_DISCOUNT
	{
		get
		{
			return this._T_PARTYM_DISCOUNT;
		}
		set
		{
			if ((this._T_PARTYM_DISCOUNT != value))
			{
				this._T_PARTYM_DISCOUNT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_SPDISCOUNT", DbType="NVarChar(255)")]
	public string T_PARTYM_SPDISCOUNT
	{
		get
		{
			return this._T_PARTYM_SPDISCOUNT;
		}
		set
		{
			if ((this._T_PARTYM_SPDISCOUNT != value))
			{
				this._T_PARTYM_SPDISCOUNT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_CASHDISCOUNT", DbType="NVarChar(255)")]
	public string T_PARTYM_CASHDISCOUNT
	{
		get
		{
			return this._T_PARTYM_CASHDISCOUNT;
		}
		set
		{
			if ((this._T_PARTYM_CASHDISCOUNT != value))
			{
				this._T_PARTYM_CASHDISCOUNT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PARTYM_GSTNUM", DbType="NVarChar(255)")]
	public string T_PARTYM_GSTNUM
	{
		get
		{
			return this._T_PARTYM_GSTNUM;
		}
		set
		{
			if ((this._T_PARTYM_GSTNUM != value))
			{
				this._T_PARTYM_GSTNUM = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_RM_MASTER")]
public partial class T_RM_MASTER
{
	
	private int _ID;
	
	private string _T_RMM_BILL;
	
	private System.DateTime _T_RMM_PDATE;
	
	private string _T_RMM_UNITNUM;
	
	private string _T_RMM_PARTY;
	
	private string _T_RMM_SECTION;
	
	private double _T_RMM_QUANTITY;
	
	private double _T_RMM_RATE;
	
	private System.Nullable<double> _T_RMM_TOTALAMNT;
	
	private System.DateTime _T_RMM_EDATE;
	
	public T_RM_MASTER()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_BILL", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string T_RMM_BILL
	{
		get
		{
			return this._T_RMM_BILL;
		}
		set
		{
			if ((this._T_RMM_BILL != value))
			{
				this._T_RMM_BILL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_PDATE", DbType="Date NOT NULL")]
	public System.DateTime T_RMM_PDATE
	{
		get
		{
			return this._T_RMM_PDATE;
		}
		set
		{
			if ((this._T_RMM_PDATE != value))
			{
				this._T_RMM_PDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_UNITNUM", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
	public string T_RMM_UNITNUM
	{
		get
		{
			return this._T_RMM_UNITNUM;
		}
		set
		{
			if ((this._T_RMM_UNITNUM != value))
			{
				this._T_RMM_UNITNUM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_PARTY", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string T_RMM_PARTY
	{
		get
		{
			return this._T_RMM_PARTY;
		}
		set
		{
			if ((this._T_RMM_PARTY != value))
			{
				this._T_RMM_PARTY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_SECTION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string T_RMM_SECTION
	{
		get
		{
			return this._T_RMM_SECTION;
		}
		set
		{
			if ((this._T_RMM_SECTION != value))
			{
				this._T_RMM_SECTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_QUANTITY", DbType="Float NOT NULL")]
	public double T_RMM_QUANTITY
	{
		get
		{
			return this._T_RMM_QUANTITY;
		}
		set
		{
			if ((this._T_RMM_QUANTITY != value))
			{
				this._T_RMM_QUANTITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_RATE", DbType="Float NOT NULL")]
	public double T_RMM_RATE
	{
		get
		{
			return this._T_RMM_RATE;
		}
		set
		{
			if ((this._T_RMM_RATE != value))
			{
				this._T_RMM_RATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_TOTALAMNT", DbType="Float")]
	public System.Nullable<double> T_RMM_TOTALAMNT
	{
		get
		{
			return this._T_RMM_TOTALAMNT;
		}
		set
		{
			if ((this._T_RMM_TOTALAMNT != value))
			{
				this._T_RMM_TOTALAMNT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_RMM_EDATE", DbType="DateTime NOT NULL")]
	public System.DateTime T_RMM_EDATE
	{
		get
		{
			return this._T_RMM_EDATE;
		}
		set
		{
			if ((this._T_RMM_EDATE != value))
			{
				this._T_RMM_EDATE = value;
			}
		}
	}
}
#pragma warning restore 1591
